language: node_js
node_js:
  - 12.6.0
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - openssl enc -aes-256-cbc -k "$super_secret_password" -md sha512 -salt -in ./.travis/id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
  - chmod 600 ~/.ssh/id_rsa_travis
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa_travis
  - cp ./.travis/ssh_config ~/.ssh/config
  - git config --global user.name JoashZhao
  - git config --global user.email 1143768516@qq.com
install:
  - npm install hexo-cli -g
  - npm install
script:
  - npm run deploy